version: "3.8"

services:
  nginx:
    build: ./nginx
    image: nginx:latest
    container_name: nginx_cont
    ports:
      - "80:80"
    restart: always
    networks:
      - notes-app-nw

  web:
    image: kapilnam09/notes-app:latest       
    container_name: web_cont
    ports:
      - "8000:8000"                 # Only for deployment
    depends_on:
          db: 
            condition: service_healthy
    networks:
      - notes-app-nw

  db:
    image: mysql:latest
    container_name: db_cont
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
    volumes:
      - ./data/mysql/db:/var/lib/mysql
    healthcheck:
  test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uroot", "-proot"]
  interval: 10s
  timeout: 5s
  retries: 10
  start_period: 120s
    networks:
      - notes-app-nw

networks:
  notes-app-nw:
